"use client";

import {
  RiAddCircleLine,
  RiAddLine,
  RiAlertLine,
  RiAlignCenter,
  RiAlignJustify,
  RiAlignLeft,
  RiAlignRight,
  RiAppsLine,
  RiArrowDownLine,
  RiArrowDownSLine,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,
  RiCpuLine,
  RiPlayLine,
  RiStopLine,
  RiThumbUpLine,
  RiTranslate,
  RiVolumeUpLine,
  RiArrowLeftLine,
  RiArrowLeftRightLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowRightUpLine,
  RiArrowUpLine,
  RiArrowUpSLine,
  RiArticleLine,
  RiBankCardLine,
  RiBarChartLine,
  RiBold,
  RiBook2Line,
  RiBookLine,
  RiBookMarkedLine,
  RiBookOpenLine,
  RiBookmarkLine,
  RiBrainLine,
  RiBrushLine,
  RiBuilding2Line,
  RiBuildingLine,
  RiCalendar2Line,
  RiCalendarCheckLine,
  RiCalendarLine,
  RiChat3Line,
  RiChatQuoteLine,
  RiChatSmile2Line,
  RiChatSmile3Line,
  RiCheckDoubleLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCheckboxMultipleLine,
  RiClapperboardAiLine,
  RiClipboardLine,
  RiCloseLine,
  RiCloudy2Fill,
  RiCodeFill,
  RiCodeLine,
  RiCoinLine,
  RiCommunityLine,
  RiCompassLine,
  RiCopperCoinLine,
  RiCustomerService2Line,
  RiDashboardLine,
  RiDeleteBin6Line,
  RiDeleteBinLine,
  RiDiceLine,
  RiDiscLine,
  RiDiscordFill,
  RiDiscordLine,
  RiDiscussLine,
  RiDoubleQuotesL,
  RiDownload2Line,
  RiDownloadLine,
  RiEarthLine,
  RiEdit2Line,
  RiEditLine,
  RiEmotionHappyLine,
  RiEmotionLaughLine,
  RiEmotionSadFill,
  RiEqualizerLine,
  RiEraserLine,
  RiErrorWarningLine,
  RiExpandDiagonalLine,
  RiExpandUpDownLine,
  RiExternalLinkLine,
  RiEyeLine,
  RiFileCopyLine,
  RiFileList3Line,
  RiFilePdf2Line,
  RiFileReduceLine,
  RiFileTextFill,
  RiFileTextLine,
  RiFileWordLine,
  RiFingerprint2Line,
  RiFireLine,
  RiFlagLine,
  RiFlashlightFill,
  RiFlashlightLine,
  RiFocus3Line,
  RiFocusLine,
  RiFolderLine,
  RiFullscreenExitLine,
  RiFullscreenLine,
  RiGamepadLine,
  RiGiftLine,
  RiGithubFill,
  RiGithubLine,
  RiGlobalLine,
  RiGraduationCapLine,
  RiGridLine,
  RiGroupLine,
  RiH1,
  RiH2,
  RiH3,
  RiHammerLine,
  RiHashtag,
  RiHeadphoneLine,
  RiHeart3Fill,
  RiHeart3Line,
  RiHeartLine,
  RiHistoryLine,
  RiHome4Line,
  RiHomeHeartLine,
  RiHomeLine,
  RiImageLine,
  RiInformationLine,
  RiInputMethodFill,
  RiInstagramLine,
  RiItalic,
  RiKey2Fill,
  RiKey2Line,
  RiLayoutGridLine,
  RiLayoutMasonryLine,
  RiLeafLine,
  RiLightbulbFlashLine,
  RiLightbulbLine,
  RiLineChartLine,
  RiLink,
  RiLinkUnlink,
  RiLinksLine,
  RiLock2Line,
  RiListCheck2,
  RiListOrdered,
  RiListUnordered,
  RiLoader2Line,
  RiLoader4Line,
  RiMagicLine,
  RiMailLine,
  RiMapLine,
  RiMapPin2Line,
  RiMarkPenLine,
  RiMarkdownLine,
  RiMegaphoneLine,
  RiMic2Line,
  RiMicLine,
  RiMessage2Line,
  RiMessage3Line,
  RiMoneyCnyCircleFill,
  RiMoneyDollarBoxLine,
  RiMoonLine,
  RiMoreLine,
  RiMotorbikeLine,
  RiMovie2Line,
  RiMusic2Line,
  RiNextjsFill,
  RiNodeTree,
  RiOrderPlayLine,
  RiPaintFill,
  RiPaletteLine,
  RiPauseCircleLine,
  RiPenNibLine,
  RiPencilLine,
  RiPhoneLine,
  RiPlanetLine,
  RiPlayCircleLine,
  RiPriceTag3Line,
  RiQuillPenLine,
  RiRefreshLine,
  RiRepeat2Line,
  RiReplyLine,
  RiRobot2Line,
  RiRocket2Line,
  RiRocketLine,
  RiRouteLine,
  RiSave3Line,
  RiScales3Line,
  RiScissorsCutLine,
  RiSearchEyeLine,
  RiSearchLine,
  RiSendPlane2Fill,
  RiSendPlaneLine,
  RiSeparator,
  RiSettings3Line,
  RiShare2Line,
  RiShareForwardLine,
  RiShareLine,
  RiShieldCheckLine,
  RiShieldStarLine,
  RiShuffleLine,
  RiSideBarLine,
  RiSmartphoneLine,
  RiSparkling2Line,
  RiSparklingLine,
  RiSpeedLine,
  RiStackLine,
  RiStarLine,
  RiStarSmileLine,
  RiStopFill,
  RiStrikethrough,
  RiSubtractLine,
  RiSwordLine,
  RiTableLine,
  RiTeamLine,
  RiTestTubeLine,
  RiText,
  RiTimeLine,
  RiToolsLine,
  RiTrophyLine,
  RiTwitterLine,
  RiTwitterXFill,
  RiUnderline,
  RiUpload2Line,
  RiUser3Line,
  RiUserHeartLine,
  RiUserLine,
  RiUserSharedLine,
  RiUserSmileLine,
  RiUserStarLine,
  RiUserVoiceLine,
  RiVipCrownLine,
  RiYoutubeLine,
} from "react-icons/ri";
import type { IconType } from "react-icons";
import { memo } from "react";

const remixIcons: Record<string, IconType> = {
  RiAddCircleLine,
  RiAddLine,
  RiAlertLine,
  RiAlignCenter,
  RiAlignJustify,
  RiAlignLeft,
  RiAlignRight,
  RiAppsLine,
  RiArrowDownLine,
  RiArrowDownSLine,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,
  RiCpuLine,
  RiImageLine,
  RiPlayLine,
  RiStopLine,
  RiText,
  RiThumbUpLine,
  RiTranslate,
  RiVolumeUpLine,
  RiArrowLeftLine,
  RiArrowLeftRightLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowRightUpLine,
  RiArrowUpLine,
  RiArrowUpSLine,
  RiArticleLine,
  RiBankCardLine,
  RiBarChartLine,
  RiBold,
  RiBook2Line,
  RiBookLine,
  RiBookMarkedLine,
  RiBookOpenLine,
  RiBookmarkLine,
  RiBrainLine,
  RiBrushLine,
  RiBuilding2Line,
  RiBuildingLine,
  RiCalendar2Line,
  RiCalendarCheckLine,
  RiCalendarLine,
  RiChat3Line,
  RiChatQuoteLine,
  RiChatSmile2Line,
  RiChatSmile3Line,
  RiCheckDoubleLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCheckboxMultipleLine,
  RiClapperboardAiLine,
  RiClipboardLine,
  RiCloseLine,
  RiCloudy2Fill,
  RiCodeFill,
  RiCodeLine,
  RiCoinLine,
  RiCommunityLine,
  RiCompassLine,
  RiCopperCoinLine,
  RiCustomerService2Line,
  RiDashboardLine,
  RiDeleteBin6Line,
  RiDeleteBinLine,
  RiDiceLine,
  RiDiscLine,
  RiDiscordFill,
  RiDiscordLine,
  RiDiscussLine,
  RiDoubleQuotesL,
  RiDownload2Line,
  RiDownloadLine,
  RiEarthLine,
  RiEdit2Line,
  RiEditLine,
  RiEmotionHappyLine,
  RiEmotionLaughLine,
  RiEmotionSadFill,
  RiEqualizerLine,
  RiEraserLine,
  RiErrorWarningLine,
  RiExpandDiagonalLine,
  RiExpandUpDownLine,
  RiExternalLinkLine,
  RiEyeLine,
  RiFileCopyLine,
  RiFileList3Line,
  RiFilePdf2Line,
  RiFileReduceLine,
  RiFileTextFill,
  RiFileTextLine,
  RiFileWordLine,
  RiFingerprint2Line,
  RiFireLine,
  RiFlagLine,
  RiFlashlightFill,
  RiFlashlightLine,
  RiFocus3Line,
  RiFocusLine,
  RiFolderLine,
  RiFullscreenExitLine,
  RiFullscreenLine,
  RiGamepadLine,
  RiGiftLine,
  RiGithubFill,
  RiGithubLine,
  RiGlobalLine,
  RiGraduationCapLine,
  RiGridLine,
  RiGroupLine,
  RiH1,
  RiH2,
  RiH3,
  RiHammerLine,
  RiHashtag,
  RiHeadphoneLine,
  RiHeart3Fill,
  RiHeart3Line,
  RiHeartLine,
  RiHistoryLine,
  RiHome4Line,
  RiHomeHeartLine,
  RiHomeLine,
  RiInformationLine,
  RiInputMethodFill,
  RiInstagramLine,
  RiItalic,
  RiKey2Fill,
  RiKey2Line,
  RiLayoutGridLine,
  RiLayoutMasonryLine,
  RiLeafLine,
  RiLightbulbFlashLine,
  RiLightbulbLine,
  RiLineChartLine,
  RiLink,
  RiLinkUnlink,
  RiLinksLine,
  RiLock2Line,
  RiListCheck2,
  RiListOrdered,
  RiListUnordered,
  RiLoader2Line,
  RiLoader4Line,
  RiMagicLine,
  RiMailLine,
  RiMapLine,
  RiMapPin2Line,
  RiMarkPenLine,
  RiMarkdownLine,
  RiMegaphoneLine,
  RiMic2Line,
  RiMicLine,
  RiMessage2Line,
  RiMessage3Line,
  RiMoneyCnyCircleFill,
  RiMoneyDollarBoxLine,
  RiMoonLine,
  RiMoreLine,
  RiMotorbikeLine,
  RiMovie2Line,
  RiMusic2Line,
  RiNextjsFill,
  RiNodeTree,
  RiOrderPlayLine,
  RiPaintFill,
  RiPaletteLine,
  RiPauseCircleLine,
  RiPenNibLine,
  RiPencilLine,
  RiPhoneLine,
  RiPlanetLine,
  RiPlayCircleLine,
  RiPriceTag3Line,
  RiQuillPenLine,
  RiRefreshLine,
  RiRepeat2Line,
  RiReplyLine,
  RiRobot2Line,
  RiRocket2Line,
  RiRocketLine,
  RiRouteLine,
  RiSave3Line,
  RiScales3Line,
  RiScissorsCutLine,
  RiSearchEyeLine,
  RiSearchLine,
  RiSendPlane2Fill,
  RiSendPlaneLine,
  RiSeparator,
  RiSettings3Line,
  RiShare2Line,
  RiShareForwardLine,
  RiShareLine,
  RiShieldCheckLine,
  RiShieldStarLine,
  RiShuffleLine,
  RiSideBarLine,
  RiSmartphoneLine,
  RiSparkling2Line,
  RiSparklingLine,
  RiSpeedLine,
  RiStackLine,
  RiStarLine,
  RiStarSmileLine,
  RiStopFill,
  RiStrikethrough,
  RiSubtractLine,
  RiSwordLine,
  RiTableLine,
  RiTeamLine,
  RiTestTubeLine,
  RiTimeLine,
  RiToolsLine,
  RiTrophyLine,
  RiTwitterLine,
  RiTwitterXFill,
  RiUnderline,
  RiUpload2Line,
  RiUser3Line,
  RiUserHeartLine,
  RiUserLine,
  RiUserSharedLine,
  RiUserSmileLine,
  RiUserStarLine,
  RiUserVoiceLine,
  RiVipCrownLine,
  RiYoutubeLine,
};

/**
 * Legacy/alias names that appeared in page copy (lucide-style kebab names,
 * GoIcons names) or older code. Resolved to the canonical RemixIcon entry so
 * unknown names degrade to a close brand icon instead of rendering nothing.
 */
const iconAliases: Record<string, string> = {
  analyze: "RiLineChartLine",
  "arrow-right": "RiArrowRightLine",
  "book-open": "RiBookOpenLine",
  BookOpen: "RiBookOpenLine",
  building: "RiBuilding2Line",
  check: "RiCheckLine",
  "check-circle": "RiCheckboxCircleLine",
  "chevron-down": "RiArrowDownSLine",
  "chevron-right": "RiArrowRightSLine",
  clapperboard: "RiClapperboardAiLine",
  clock: "RiTimeLine",
  close: "RiCloseLine",
  copy: "RiFileCopyLine",
  Copy: "RiFileCopyLine",
  cpu: "RiCpuLine",
  download: "RiDownloadLine",
  edit: "RiEditLine",
  feather: "RiQuillPenLine",
  gamepad: "RiGamepadLine",
  globe: "RiGlobalLine",
  GoArrowUpRight: "RiArrowRightUpLine",
  GoRocket: "RiRocket2Line",
  GoThumbsup: "RiThumbUpLine",
  "graduation-cap": "RiGraduationCapLine",
  heart: "RiHeartLine",
  Heart: "RiHeartLine",
  history: "RiHistoryLine",
  image: "RiImageLine",
  Image: "RiImageLine",
  info: "RiInformationLine",
  languages: "RiTranslate",
  lightbulb: "RiLightbulbLine",
  megaphone: "RiMegaphoneLine",
  "message-circle": "RiChat3Line",
  palette: "RiPaletteLine",
  "pen-tool": "RiPenNibLine",
  Play: "RiPlayLine",
  plus: "RiAddLine",
  refresh: "RiRefreshLine",
  "refresh-cw": "RiRefreshLine",
  RiAlgorithmFill: "RiCpuLine",
  RiGemLine: "RiSparkling2Line",
  RiGitCompareLine: "RiArrowLeftRightLine",
  RiLinkLine: "RiLinksLine",
  RiScrollLine: "RiBookOpenLine",
  RiSlidersLine: "RiEqualizerLine",
  save: "RiSave3Line",
  Search: "RiSearchLine",
  settings: "RiSettings3Line",
  "shield-check": "RiShieldCheckLine",
  shuffle: "RiShuffleLine",
  sliders: "RiEqualizerLine",
  sparkles: "RiSparkling2Line",
  Sparkles: "RiSparkling2Line",
  Square: "RiStopLine",
  "volume-2": "RiVolumeUpLine",
  Volume2: "RiVolumeUpLine",
  zap: "RiFlashlightLine",
};

function resolveIcon(name: string): IconType | undefined {
  return remixIcons[name] ?? remixIcons[iconAliases[name]];
}

const Icon = memo(function Icon({
  name,
  className,
  onClick,
}: {
  name: string;
  className?: string;
  onClick?: () => void;
}) {
  const IconComponent = resolveIcon(name);

  if (!IconComponent) return null;

  return (
    <IconComponent
      className={`${className} cursor-pointer`}
      onClick={onClick}
      style={{ cursor: onClick ? "pointer" : "default" }}
    />
  );
});

export default Icon;
